# -*- coding: utf-8 -*-
"""Logic 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlfLDqP9xLH6QpHe_mCdBYaCCqOrMUbh
"""

def crange(a,b):
    return range(a, b + 1)
def printnln(a):
    print(a, end="")

#SOAL 1

for y in crange(1,9):
    for x in crange(1,9):
        if x == y:
            printnln("*")
        else:
            printnln("_")
    print()

#SOAL 2

for y in crange(1,9):
    for x in crange(1,9):
        if x == 9 - (y - 1):
            printnln("*")
        else:
            printnln("_")
    print()

#SOAL 3

for y in crange(1,9):
    for x in crange(1,9):
        if x == y or x == 9 - (y - 1):
            printnln("*")
        else:
            printnln("_")
    print()

#SOAL 4

for y in crange(1,9):
    for x in crange(1,9):
        if x == y:
            printnln("*")
        elif  x == 9 - (y - 1):
            printnln("*")
        elif x ==5:
            printnln("*")
        elif y == 5:
            printnln("*")
        else:
            printnln("-")

    print()

#SOAL 5

for y in crange(1,9):
    for x in crange(1,9):
        if x <= y:
            printnln("*")
        else:
            printnln("_")

    print()

#SOAL 6

for y in crange(1,9):
    for x in crange(1,9):
        if x >= y:
            printnln("*")
        else:
            printnln("_")

    print()

#SOAL 7

for y in crange(1,9):
    for x in crange(1,9):
        if x >= y and x <= 9 - (y-1):
            printnln("*")
        elif x <= y and x >= 9 - (y-1):
            printnln("*")
        else:
            printnln("_")

    print()

#SOAL 8

for y in crange(1,9):
    for x in crange(1,9):
        if x <= y and x <= 9 - (y - 1):
            printnln("*")
        elif x >= y and x >= 9 - (y - 1):
            printnln("*")
        else:
            printnln("_")

    print()